<a href="https://colab.research.google.com/github/CE605A/Ajay-S_231030003/blob/main/CE605_231030003_Programming_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Create a row and column vector using input method and manually.
# Using input method
#Creating row vector
import numpy as np
row=input("Enter the row vector elements")
row_vector=[int(x) for x in row.split()]
row_input=np.array(row_vector)
#Creating column vector
import numpy as np
column=input("Enter the column vector elemnts ")
column_vector=[int(x) for x in column.split()]
column_input=np.array(column_vector).reshape(-1,1)

#Using manually
# To get the row vector
import numpy as np
rowvector=[1,2,3,4]
r=np.array(rowvector)
#To get the column vector
import numpy as np
columnvector=[[5],
               [6],
              [7],
              [8]]
c=np.array(columnvector)

#To print the outputs
print("Row vector using input method",row_input)
print("Column vector using input method",column_input)
print("Row vector using manually",r)
print("Column vector using manually",c)



Enter the row vector elements1 2 3 4
Enter the column vector elemnts 5 6 7 8
Row vector using input method [1 2 3 4]
Column vector using input method [[5]
 [6]
 [7]
 [8]]
Row vector using manually [1 2 3 4]
Column vector using manually [[5]
 [6]
 [7]
 [8]]


In [ ]:
# 2. Create a matrix (5x5) using input method as well as manually and save it as"a"
# (5x5) matrix using input method
import numpy as np
a=[]
print("Enter the elements of the matrix")
for i in range(5):
  row=[]
  for j in range(5):
    elements=int(input(f"Enter the elements at {i+1},{j+1} :"))
    row.append(elements)
  a.append(row)

a=np.array(a)
#To print the (5x5) matrix
print("The (5x5) 'a' matrix is = ",a)

#Create (5x5) matrix manually
import numpy as np
a_manual=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a_manual=np.array(a_manual)
#To print the (5x5) matrix obtained using manually
print("The (5x5) matrix 'a'(manual)",a_manual)





Enter the elements of the matrix
Enter the elements at 1,1 :1
Enter the elements at 1,2 :2
Enter the elements at 1,3 :3
Enter the elements at 1,4 :4
Enter the elements at 1,5 :5
Enter the elements at 2,1 :6
Enter the elements at 2,2 :7
Enter the elements at 2,3 :8
Enter the elements at 2,4 :9
Enter the elements at 2,5 :10
Enter the elements at 3,1 :11
Enter the elements at 3,2 :12
Enter the elements at 3,3 :13
Enter the elements at 3,4 :14
Enter the elements at 3,5 :15
Enter the elements at 4,1 :16
Enter the elements at 4,2 :17
Enter the elements at 4,3 :18
Enter the elements at 4,4 :19
Enter the elements at 4,5 :20
Enter the elements at 5,1 :21
Enter the elements at 5,2 :22
Enter the elements at 5,3 :23
Enter the elements at 5,4 :24
Enter the elements at 5,5 :25
The (5x5) 'a' matrix is =  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
The (5x5) matrix 'a'(manual) [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22

In [ ]:
# 3. Get 3rd row out of the matrix
#The (5x5) "a" matrix
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#third row from the matrix
third_row=a[2]
# To print the output
print("The 3rd row of the matrix is: ",third_row)

The 3rd row of the matrix is:  [11 12 13 14 15]


In [ ]:
# 4. Get the fourth column out of the matrix
# (5x5) "a" matrix
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#fourth column from the matrix
column_number=3
fourth_column=[row[column_number] for row in a]
print("The fourth column of a matrix",fourth_column)

The fourth column of a matrix [4, 9, 14, 19, 24]


In [ ]:
# 5. Sort matrix row wise and column wise
# (5x5) "a" matrix
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#To sort row wise and column wise
#To sort row wise
row_wise=np.sort(a,axis=1)

print("Matrix sorted row wise is: ",row_wise)

#To sort column wise
column_wise=np.sort(a,axis=0)
print("Matrix column wise sorted is: ",column_wise)

Matrix sorted row wise is:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Matrix column wise sorted is:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# 6. Apply for loop in matrix, if element is greater than 2, multiply element by 10 say it as "b"
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#for loop
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    if a[i][j]>2:
       a[i][j]=a[i][j]*10
b=a  #To save matrix as "b"
#To print the final matrix
print("The final matrix is: ",b)



The final matrix is:  [[  1   2  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]
 [160 170 180 190 200]
 [210 220 230 240 250]]


In [ ]:
# 7. Add a and b
#"a" matrix
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#"b" matrix
import numpy as np
b=[[1,2,30,40,50],
   [60,70,80,90,100],
   [110,120,130,140,150],
   [160,170,180,190,200],
   [210,220,230,240,250]]
b=np.array(b)

#sum a matrix a and b
sum=a+b
print("The sum of the matrix is= ",sum)



The sum of the matrix is=  [[  2   4  33  44  55]
 [ 66  77  88  99 110]
 [121 132 143 154 165]
 [176 187 198 209 220]
 [231 242 253 264 275]]


In [ ]:
# 8. Subtract b from a
#"a" matrix
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#"b" matrix
import numpy as np
b=[[1,2,30,40,50],
   [60,70,80,90,100],
   [110,120,130,140,150],
   [160,170,180,190,200],
   [210,220,230,240,250]]
b=np.array(b)

#Subtract a matrix a and b
subtraction=a-b
print("The sum of the matrix is= ",subtraction)



The sum of the matrix is=  [[   0    0  -27  -36  -45]
 [ -54  -63  -72  -81  -90]
 [ -99 -108 -117 -126 -135]
 [-144 -153 -162 -171 -180]
 [-189 -198 -207 -216 -225]]


In [ ]:
# 9. Multipication a by b element wise and matrix multiplication
#"a" matrix
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#"b" matrix
import numpy as np
b=[[1,2,30,40,50],
   [60,70,80,90,100],
   [110,120,130,140,150],
   [160,170,180,190,200],
   [210,220,230,240,250]]
b=np.array(b)

#Element wise multiplication
element_wise_multi=a*b
print("The element wise multiplication matrix is= ",element_wise_multi)

#Matrix multiplication
matrix_multi=np.dot(a,b)
print("Matrix multiplication value = ",matrix_multi)



The element wise multiplication matrix is=  [[   1    4   90  160  250]
 [ 360  490  640  810 1000]
 [1210 1440 1690 1960 2250]
 [2560 2890 3240 3610 4000]
 [4410 4840 5290 5760 6250]]
Matrix multiplication value =  [[ 2141  2282  2450  2600  2750]
 [ 4846  5192  5700  6100  6500]
 [ 7551  8102  8950  9600 10250]
 [10256 11012 12200 13100 14000]
 [12961 13922 15450 16600 17750]]


In [ ]:
# 10. Divide each element of matrix a and b by 18
#"a" matrix
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#"b" matrix
import numpy as np
b=[[1,2,30,40,50],
   [60,70,80,90,100],
   [110,120,130,140,150],
   [160,170,180,190,200],
   [210,220,230,240,250]]
b=np.array(b)

#Divide element of a by 18
a_division=a/18
print("The resulting 'a' matrix is=",a_division)

#Divide element of b by 18
b_division=b/18
print("The resulting 'b' matrix is= ",b_division)

The resulting 'a' matrix is= [[0.05555556 0.11111111 0.16666667 0.22222222 0.27777778]
 [0.33333333 0.38888889 0.44444444 0.5        0.55555556]
 [0.61111111 0.66666667 0.72222222 0.77777778 0.83333333]
 [0.88888889 0.94444444 1.         1.05555556 1.11111111]
 [1.16666667 1.22222222 1.27777778 1.33333333 1.38888889]]
The resulting 'b' matrix is=  [[ 0.05555556  0.11111111  1.66666667  2.22222222  2.77777778]
 [ 3.33333333  3.88888889  4.44444444  5.          5.55555556]
 [ 6.11111111  6.66666667  7.22222222  7.77777778  8.33333333]
 [ 8.88888889  9.44444444 10.         10.55555556 11.11111111]
 [11.66666667 12.22222222 12.77777778 13.33333333 13.88888889]]


In [ ]:
# 11. Find the inverse,rank, condition number, singular value decomposition, and the norm of the matrices a and b
#"a" matrix
import numpy as np
a=[[1,2,3,4,5],
   [6,7,8,9,10],
   [11,12,13,14,15],
   [16,17,18,19,20],
   [21,22,23,24,25]]
a=np.array(a)
#"b" matrix
import numpy as np
b=[[1,2,30,40,50],
   [60,70,80,90,100],
   [110,120,130,140,150],
   [160,170,180,190,200],
   [210,220,230,240,250]]
b=np.array(b)


# Inverse of matrices a and b
try:

   a_inverse=np.linalg.inv(a)
   b_inverse=np.linalg.inv(b)

# To print the inverse of matrices
   print("The inverse of matrix 'a' is = ",a_inverse)
   print("The inverse of matrix 'b' is = ",b_inverse)

# The given matrices are singular matrix
except np.linalg.LinAlgError:
  print("There is no inverse for the matrices as the matrices are singular")


# Rank of the matrices a and b
a_rank=np.linalg.matrix_rank(a)
b_rank=np.linalg.matrix_rank(b)

#To print the rank of matrices
print("The rank of the matrix 'a' is = ",a_rank)
print("The rank of the matrix 'b' is = ",b_rank)

# Condition number of matrices a and b
a_cond=np.linalg.cond(a)
b_cond=np.linalg.cond(b)
# To print the condition number of matrices a and b
print("The condition number of matrix 'a'=",a_cond)
print("The condition number of matrix 'b' =",a_cond)

# Singular value decomoposition of matrices a and b
a_u,a_s,a_v=np.linalg.svd(a)
b_u,b_s,b_v=np.linalg.svd(a)
# To print the svd of matrices a and b
print("The singular value decomposition of matrix 'a'- 'u','s','v':",a_u,a_s,a_v)
print("The singualr value decomposition of matrix 'b'-'u','s','v':",b_u,b_s,b_v)

#Norm of matrices a and b
a_norm=np.linalg.norm(a)
b_norm=np.linalg.norm(b)
# To print norm of matrices a and b
print("The norm of matrix 'a' =",a_norm)
print("The norm of matrix 'b' =",b_norm)


There is no inverse for the matrices as the matrices are singular
The rank of the matrix 'a' is =  2
The rank of the matrix 'b' is =  3
The condition number of matrix 'a'= 3.5675570478720614e+17
The condition number of matrix 'b' = 3.5675570478720614e+17
The singular value decomposition of matrix 'a'- 'u','s','v': [[-0.09359323 -0.76892152  0.61130515  0.0196316  -0.16099879]
 [-0.24363203 -0.49055421 -0.5142169  -0.45682855  0.4763283 ]
 [-0.39367083 -0.2121869  -0.3594458   0.81870773 -0.02272392]
 [-0.54370962  0.06618041 -0.18367831 -0.34545623 -0.73954194]
 [-0.69374842  0.34454772  0.44603585 -0.03605456  0.44693633]] [7.42540539e+01 3.36681954e+00 2.98266488e-15 1.53916447e-15
 2.08136977e-16] [[-0.39262281 -0.41913118 -0.44563955 -0.47214793 -0.4986563 ]
 [ 0.667718    0.35260325  0.0374885  -0.27762625 -0.592741  ]
 [ 0.5359956  -0.50603463 -0.52349916  0.42111979  0.0724184 ]
 [-0.33541664  0.36000724 -0.21070021  0.68304527 -0.49693566]
 [ 0.01429645 -0.56064583  0.69394096 

In [ ]:
# 12. Find the norm, inner product and outer product of column vector
#To create a column vector
import numpy as np
column=input("Enter the column elements: ")
column_vector=[int(x) for x in column.split()]
column_input=np.array(column_vector).reshape(-1,1)

#Norm of column vector
column_norm=np.linalg.norm(column_input)
# To print result
print("The norm of column vector is= ",column_norm)

#Inner product of the column vector
column_inner_product=np.dot(column_input.T,column_input)
#To print the result
print("The inner product of the column vector= ",column_inner_product)

#Outer product of column vector
column_outer_product=np.outer(column_input,column_input)
#To print the result
print("The outer product of column vector = ",column_outer_product)

Enter the column elements: 1 2 3 4
The norm of column vector is=  5.477225575051661
The inner product of the column vector=  [[30]]
The outer product of column vector =  [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
# 13. Write a function called derivative which takes input parameters f(x), a, method (forward,backward
#and central) and h(step size) (with default values method=‘central’ and h = 0.01) and returns the
#corresponding difference formula for derivative of function at a with step size h and then test your
#function on e^x and cos x at x = 0.5
import numpy as np
def derivative(f,a,method='central',h=0.01):
  if method=='forward':
    return((f(a+h)-f(a))/h)
  elif method=='backward':
    return((f(a)-f(a-h))/h)
  elif method=='central':
    return((f(a+h)-f(a-h))/(2*h))
  else:
    raise ValueError("Choose from forward, backward, or central")

# To define the function and test the derivative function
def exponential(x):
  return np.exp(x)
def cosine(x):
  return np.cos(x)
x_value=0.5

print("The derivative of e^x at x=",x_value,"from central difference is=",derivative(exponential,x_value))
print("The derivative of cosx at x=",x_value,"from central difference is=",derivative(cosine,x_value))


The derivative of e^x at x= 0.5 from central difference is= 1.648748749525375
The derivative of cosx at x= 0.5 from central difference is= -0.4794175482185081


In [ ]:
# 14. Download the Automatic Weather Station AWS Data. Read the .csv file using pandas library as a DataFrame
import pandas as pd
#Path of the csv file
input_file='/content/drive/MyDrive/AWS.csv'
#To read the csv file and create a dataframe
data_frame=pd.read_csv(input_file)
#data_frame is pandas dataframe with the data and to display first few rows of the DataFrame
print(data_frame.head(15))







                   created_at  entry_id  Soil Temperature  Soil Moisture  \
0   2022-12-14T14:19:11+05:30     10830             21.06            817   
1   2022-12-14T14:20:13+05:30     10831             21.06            817   
2   2022-12-14T14:21:15+05:30     10832             21.06            817   
3   2022-12-14T14:22:18+05:30     10833             21.06            817   
4   2022-12-14T14:23:20+05:30     10834             21.06            817   
5   2022-12-14T14:24:23+05:30     10835             21.06            817   
6   2022-12-14T14:25:25+05:30     10836             21.06            817   
7   2022-12-14T14:46:42+05:30     10837             20.87            816   
8   2022-12-14T15:17:36+05:30     10838             20.87            816   
9   2022-12-14T15:57:37+05:30     10839             20.81            815   
10  2022-12-14T16:17:37+05:30     10840             20.56            816   
11  2022-12-14T16:37:36+05:30     10841             20.37            816   
12  2022-12-